### ISSUE TITLE
YAML Export not working in version 2.0

### ISSUE THREAD

**Issue by hesselonline** [f2calv/yamlizr#175] opened 2022-12-22 11:12 UTC
**Key**
Release 2.0 breaks the exporting of YAML for us, version 1.0.21 works, same command only adding full URI when using 2.0.

Command for 1.0.21 - WORKS:

yamlizr generate -pat ********* -org ***** -proj *****  -out c:/temp/yamlizer --filter "*****"

Command for 2.0 - ERROR:

yamlizr generate -pat ********* -org https://dev.azure.com/***** -proj *****  -out c:/temp/yamlizer --filter "*****"

**Describe the bug**
Error returned by tool:

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.                            at CasCap.Commands.GenerateCommand.OnExecuteAsync() in /_/src/CasCap.DevOpsYamlizrCli/Commands/GenerateCommand.cs:line 131                       at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)                                                                                                                                                   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)                                                                                                                                             at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()                    --- End of stack trace from previous location ---                                                                                                   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)                  at CasCap.Program.Main(String[] args) in /_/src/CasCap.DevOpsYamlizrCli/Program.cs:line 33                                                       at CasCap.Program.<Main>(String[] args)

**To Reproduce**
See above, we couldn't get 2.0 working.

**Expected behavior**
Export of YAML, which is not happening

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - .NET 7.0 SDK

**Additional context**

**Comment by f2calv** [comment] 2022-12-22 13:34
Fixed in 2.0.1

**Comment by f2calv** [comment] 2023-01-11 08:22
Closing as duplicate of https://github.com/f2calv/yamlizr/issues/175

**Closed by f2calv** 2023-01-11 08:22 UTC
Labels: bug
